# Generated by Django 5.0.6 on 2024-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=10)),
                ('brand_model', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('car_image', models.ImageField(upload_to='car_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
